
# Docker Configuration
docker:
  # Docker server address (modify as needed)
  # (for example: tcp://127.0.0.1:2375 or unix:///var/run/docker.sock)
  host: "unix:///var/run/docker.sock" 

  # TLS Configuration
  # Uncomment the following lines to enable TLS
  tls:
    # Enable TLS
    enabled: false
    # Path to CA certificate for TLS verification
    verify: "/path/to/ca.pem"  
    # Path to client certificate for TLS
    cert: "/path/to/cert.pem"
    # Path to client key for TLS
    key: "/path/to/key.pem"  

# Logging Configuration (Possible values : "DEBUG", "INFO", "WARN", "ERROR", "FATAL")
logLevel:
  # General logging level for all libraries etc
  general: "INFO"
  # This application specific logging level
  application: "DEBUG"

# Traefik Specific Configuration
traefik:
  # Name of the Traefik container
  containerName: "traefik"
  # Label to monitor for Traefik management (using regex)
  monitoredLabel: "^traefik.enable$"
  # Label of traefik_network_connector network to connect to (not mandatory on services but if present, only connect to these networks)
  # For example, if you have 2 docker networks, "autoproxy.networks" label can be "autoproxy.networks=network1" to only connect to network1
  # DEPRECATED !
  # Traefik has his own label for it `traefik.docker.network`, so we stick to it. Keep this one for compatibility
  # networkLabel: "autoproxy.networks"
  # (Defaulted to traefik.docker.network)
